import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary-fixed-variant": "#004c6e",
        "secondary-fixed-dim": "#ddb7ff",
        "on-tertiary": "#00344d",
        "on-surface-variant": "#c7c4d7",
        "surface-container": "#171f33",
        background: "#0b1326",
        "secondary-container": "#6f00be",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-bright": "#31394d",
        "inverse-primary": "#494bd6",
        "surface-dim": "#0b1326",
        "on-background": "#dae2fd",
        "on-secondary-fixed-variant": "#6900b3",
        "on-secondary-fixed": "#2c0051",
        "on-error-container": "#ffdad6",
        "surface-variant": "#2d3449",
        "inverse-on-surface": "#283044",
        "on-surface": "#dae2fd",
        "primary-container": "#8083ff",
        outline: "#908fa0",
        "secondary-fixed": "#f0dbff",
        "on-secondary": "#490080",
        "inverse-surface": "#dae2fd",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-container": "#009ada",
        secondary: "#ddb7ff",
        "outline-variant": "#464554",
        "surface-container-high": "#222a3d",
        "surface-container-low": "#131b2e",
        tertiary: "#89ceff",
        "on-tertiary-container": "#002d43",
        "on-error": "#690005",
        surface: "#0b1326",
        "surface-tint": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "on-secondary-container": "#d6a9ff",
        "on-primary": "#1000a9",
        "surface-container-highest": "#2d3449",
        primary: "#c0c1ff",
        "surface-container-lowest": "#060e20",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        lg: "1.5rem",
        xl: "2rem",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        base: "4px",
        "sidebar-width": "280px",
        "2xl": "3rem",
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        button: ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        display: ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
